name: senti
description: "Senti-AI the only friend you actually need"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.4+3
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  analyzer: ^6.11.0

flutter:
  uses-material-design: true

  assets:
    - .env

  #fonts:
