name: Flutter action

on:
  push:
    branches: ["senti-ai"]
  pull_request:
    branches: ["senti-ai"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter with a specific version that includes Dart SDK 3.7.0-209.1.beta
      - uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '2.18.0'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build for web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: senti-ai
          folder: build/web
          clean: true
          commit-message: "Deploying Flutter web app"
