name: Dart CI and Deploy

on:
  push:
    branches: ["senti-ai"]
  pull_request:
    branches: ["senti-ai"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter (you can pin a specific version if desired)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build for web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: senti-ai
          folder: build/web
          clean: true
          commit_message: "Deploying Flutter web app"